### ISSUE TITLE
cannot import name ‘Mapping’ from ‘collections’

### ISSUE THREAD

**Issue by matteodanelli** [hexCut/irsap-ha#9]
**The problem**
I'm unable to load the integration

**What version of irsap-ha has the issue?**
1.3.0

**What version of hass are you using?**
2024.8.3

**What type of installation are you running?**
Home Assistant Core on Raspberry

**Where the issue happen?**
Repository added correctly. Issue arises when I try to add the integration from the setting.

**What's the error?**
A popup appears with the following message
```
Impossible to load the integration: {"message":"Invalid handler specified"}
```

**Anything in the logs that might be useful for us?**
Logs record the following
```
Error occurred loading flow for integration irsap_ha: cannot import name ‘Mapping’ from ‘collections’ (/usr/local/lib/python3.12/collections/init.py)
```

**Additional information**
I've used a fork where the only change is the version in the manifest (moved to 2024.8.3), because an upgrade of hass to 2024.9 or 2024.10 led me to continuous crashes (home assistant core has several issues opened about this :(
Therefore I haven't tested on latest home assistant version.

**Comment by valerix85** [comment]
Hi,
How about trying to edit the "manifest.json" file inside the "irsap_ha" folder located inside "custom_components"? 

You should change the line from "requirements": ["warrant"] to "requirements": ["warrant", "mapping"]

**Comment by matteodanelli** [comment]
Now the error doesn't show but it's indefinitely stuck with the loading message
_Wait, the configuration for irsap_ha is loading_

**Comment by valerix85** [comment]
It is not clear to me if the error appears after editing the file and adding the integration or if after the integration is done and then during HA booting

**Comment by matteodanelli** [comment]
When I go into settings --> integrations --> add integration --> look for irsap and press add: a popup appears with 
{"message":"Invalid handler specified"}
If at this point go into logs I see the message above about collections.

Yes, inside manifest.json I've put Mapping.

**Comment by matteodanelli** [comment]
For further analysis, I'm using python 3.12. Is the module compatible with that version?

**Comment by valerix85** [comment]
> For further analysis, I'm using python 3.12. Is the module compatible with that version?

Yes. But it’s Mapping and not mapping

**Comment by matteodanelli** [comment]
Yes, is it correct no?
https://github.com/matteodanelli/irsap-ha/blob/main/custom_components/irsap-ha/manifest.json

**Comment by valerix85** [comment]
> cannot import name ‘Mapping’ from ‘collections’

Yes, try to replace Mappings with urllib3

**Comment by matteodanelli** [comment]
collections seems to be already in python12, however urllib3 returns 
`Detected blocking call to import_module with args ('custom_components.irsap_ha.config_flow',) inside the event loop by integration 'config' at homeassistant/components/config/config_entries.py, 
line 179: return await super()._post_impl(request, data) (offender: /srv/homeassistant/lib/python3.12/site-packages/homeassistant/loader.py, 
line 1296: return importlib.import_module(f"{self.pkg_path}.{platform_name}")), please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+config%22 For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "/srv/homeassistant/bin/hass", 
line 8, in <module> sys.exit(main()) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/__main__.py", 
line 209, in main exit_code = runner.run(runtime_conf) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/runner.py", 
line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", 
line 651, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", 
line 618, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", 
line 1951, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", 
line 84, in _run self._context.run(self._callback, *self._args) File "/srv/homeassistant/lib/python3.12/site-packages/aiohttp/web_protocol.py", 
line 462, in _handle_request resp = await request_handler(request) File "/srv/homeassistant/lib/python3.12/site-packages/aiohttp/web_app.py", 
line 537, in _handle resp = await handler(request) File "/srv/homeassistant/lib/python3.12/site-packages/aiohttp/web_middlewares.py", 
line 114, in impl return await handler(request) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/http/security_filter.py", 
line 92, in security_filter_middleware return await handler(request) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/http/forwarded.py", 
line 83, in forwarded_middleware return await handler(request) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/http/request_context.py", 
line 26, in request_context_middleware return await handler(request) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/http/ban.py", 
line 85, in ban_middleware return await handler(request) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/http/auth.py", 
line 242, in auth_middleware return await handler(request) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/http/headers.py", 
line 32, in headers_middleware response = await handler(request) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/http.py", 
line 73, in handle result = await handler(request, **request.match_info) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/http/decorators.py", 
line 81, in with_admin return await func(self, request, *args, **kwargs) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/http/data_validator.py", 
line 74, in wrapper return await method(view, request, data, *args, **kwargs) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/config/config_entries.py", 
line 172, in post return await self._post_impl(request, data) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/config/config_entries.py", 
line 179, in _post_impl return await super()._post_impl(request, data)`

Seems something related to https://community.home-assistant.io/t/how-to-call-importlib-import-module-in-a-way-that-doesnt-block-the-thread/728021?

**Comment by valerix85** [comment]
This error is already fixed in the latest version, please upgrade your fork

**Comment by matteodanelli** [comment]
Yes, already updated, but maybe the add of urllib3 in the json brings it back.

**Comment by valerix85** [comment]
> collections seems to be already in python12, however urllib3 trigger another error
> 
> `Detected blocking call to import_module with args ('custom_components.irsap_ha.config_flow',) inside the event loop by integration 'config' at homeassistant/components/config/config_entries.py, line 179: return await super()._post_impl(request, data) (offender: /srv/homeassistant/lib/python3.12/site-packages/homeassistant/loader.py, line 1296: return importlib.import_module(f"{self.pkg_path}.{platform_name}")), please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+config%22 For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "/srv/homeassistant/bin/hass", line 8, in <module> sys.exit(main()) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 651, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 618, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1951, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 84, in _run self._context.run(self._callback, *self._args) File "/srv/homeassistant/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 462, in _handle_request resp = await request_handler(request) File "/srv/homeassistant/lib/python3.12/site-packages/aiohttp/web_app.py", line 537, in _handle resp = await handler(request) File "/srv/homeassistant/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl return await handler(request) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware return await handler(request) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware return await handler(request) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/http/request_context.py", line 26, in request_context_middleware return await handler(request) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/http/ban.py", line 85, in ban_middleware return await handler(request) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/http/auth.py", line 242, in auth_middleware return await handler(request) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/http/headers.py", line 32, in headers_middleware response = await handler(request) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/http.py", line 73, in handle result = await handler(request, **request.match_info) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/http/decorators.py", line 81, in with_admin return await func(self, request, *args, **kwargs) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/http/data_validator.py", line 74, in wrapper return await method(view, request, data, *args, **kwargs) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/config/config_entries.py", line 172, in post return await self._post_impl(request, data) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/config/config_entries.py", line 179, in _post_impl return await super()._post_impl(request, data)`
> 
> Seems something related to https://community.home-assistant.io/t/how-to-call-importlib-import-module-in-a-way-that-doesnt-block-the-thread/728021?

Could be, we have to refactor the code to use asynchronous loading methods where possible, especially if you’re dynamically importing parts of the integration. Home Assistant expects certain actions like loading config flows to happen asynchronously to avoid blocking.

**Comment by valerix85** [comment]
Try with the config_flow.py updated on dev branch please

**Comment by matteodanelli** [comment]
Nothing changed unfortunately, same errors

**Comment by valerix85** [comment]
@matteodanelli Hi made another changed to the config_flow.py file, please check it

**Comment by matteodanelli** [comment]
It's quite weird, but I still have the same issue. Are you able to replicate the issue? It could be my machine fault maybe..

**Comment by valerix85** [comment]
> It's quite weird, but I still have the same issue. Are you able to replicate the issue? It could be my machine fault maybe..

No, other people use it without any problems. You are the only one who has it at the moment

**Comment by valerix85** [comment]
@matteodanelli I don't know, from a HA container dev it works.
Try to use our code and not the fork, thank you

**Comment by valerix85** [comment]
@matteodanelli I pushed a modified version of the config_flow.py please try it https://github.com/hexCut/irsap-ha/commit/bcab7bf116a171183231d514105c2a841d4bd2de

**Comment by matteodanelli** [comment]
Question, do you know how to directly add that commit to hacs? Which endpoint should I specify?
